---
services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres
    env_file:
      - env/.postgres
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "keycloak", "-U", "keycloak"]
      interval: 10s
      timeout: 3s
      retries: 3
    volumes:
      - postgres:/var/lib/postgresql/data

  keycloak:
    image: jboss/keycloak:16.1.1
    container_name: keycloak
    env_file:
      - env/.credentials
      - env/.keycloak
    healthcheck:
      test: ["CMD", "curl", "-f", "http://0.0.0.0:8080/auth/realms/master"]
      start_period: 20s
      interval: 30s
      retries: 3
      timeout: 5s
    ports:
      - 8080:8080
    depends_on:
      postgres:
        condition: service_healthy

  backend:
    container_name: backend
    build:
      context: .
      tags:
        - "legit-py/backend:latest"
        - "legit-py/backend:${VERSION}"
      dockerfile: backend.Dockerfile
      labels:
        com.legit.description: "KeyCloak Realm Creation API"
        com.legit.version: "${VERSION}"
      pull: true
    ports:
      - ${APP_PORT}:${APP_PORT}
    env_file:
      - env/.env
      - env/.credentials
    depends_on:
      keycloak:
        condition: service_healthy

volumes:
  postgres: {}
  keycloak: {}
